# -*- coding: utf-8 -*-
"""For_while_loop.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1d9uI1A5Ha_6WohycNbrD4DGrAL3OU3_d

**FOR_WHILE_LOOP**

**Q1**
"""

name='Pentagon Space'
rev= ''
for i in name:
  rev=i+rev
rev

"""**Q2**"""

name='Pentagon Space'
rev=''
num=0
for i in name:
  if num<6:
    rev=i+rev
    num += 1
  else:
    rev=rev+i
rev

"""**Q3**"""

name='Pentagon Space'
unique=''
for i in name:
  if i not in unique:
    unique +=i
unique

"""**While_loop Q4**"""

name='Pentagon Space'
rev=''
k=0
while(k<len(name)):
  rev=name[k]+rev
  k=k+1
rev

"""**Q5**"""

name='Pentagon Space'
k=0
last=len(name)-5
while(k<len(name)):
  if k>last:
    rev=name[k]+rev
    k=k+1
  else:
    rev=rev+name[k]
    k=k+1
print(rev)

"""**Q6**"""

name='Pentagon Space'
k=0
unqiue=''
while(k<len(name)):
  if name[k] not in unqiue:
    unqiue +=name[k]
  k=k+1
print(unqiue)